#version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100" # HTTP API
# stick with defaults
#    command: -config.file=/etc/loki/config/loki-config.yaml
#    volumes:
#      - ./loki:/etc/loki/config

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/log/journal:/var/log/journal:ro    # read systemd journal
      - /etc/machine-id:/etc/machine-id:ro      # needed for journal metadata
      - /run/log/journal:/run/log/journal:ro    # some systems use /run/log/journal

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
#    network_mode: host
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
#    network_mode: host
    pid: host
    restart: always
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
#    network_mode: host
    ports:
      - "3000:3000" #UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
